<?php
	$db = new SQLite3("database.db");

	$db->exec("CREATE TABLE IF NOT EXISTS users(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username VARCHAR(64) NOT NULL,
		email VARCHAR(255) NOT NULL, 
		passwort VARCHAR(255) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");

	$db->exec("CREATE TABLE IF NOT EXISTS permissions(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		uid INTEGER NOT NULL,
		permission INTEGER NOT NULL, 
		developer INTEGER NOT NULL)");

	$db->exec("CREATE TABLE IF NOT EXISTS password_reset(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		uid INTEGER NOT NULL,
		key VARCHAR(16) NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");

	$db->exec("CREATE TABLE IF NOT EXISTS changelog(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		uid_creator INTEGER NOT NULL,
		header VARCHAR NOT NULL,
		change TEXT NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");

	$db->exec("CREATE TABLE IF NOT EXISTS changelog_comments(
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		uid INTEGER NOT NULL,
		comment VARCHAR NOT NULL,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
?>